name: DevOpsChallenge build and test

on:
  push:
    branches: [ "dev/devops-challenge-dotnet" ]
  pull_request:
    branches: [ "dev/devops-challenge-dotnet" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "YourStrong!Passw0rd"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v3
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build binary and package
        run: dotnet publish *.sln -o ./output
        #run: dotnet build *.sln --configuration Release

     # - name: Testing stage
        #  run: dotnet test *.sln --configuration Release --no-build --verbosity normal
        
      - name: view binary
        run: |
          ls output/
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: shehanamila/salesapi:latest
