name: DevOpsChallenge build and test

on:
  push:
    branches: [ "feature/devops-challenge-dotnet" ]
  pull_request:
    branches: [ "feature/devops-challenge-dotnet" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - uses: actions/checkout@v3
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: view binary
        run: |
          ls
